# Generated by Django 4.1.7 on 2023-04-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='days',
            new_name='days_per_month',
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='taken_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='days_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
