# Generated by Django 4.1.7 on 2023-04-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_rename_days_leave_days_per_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='taken_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
