# Generated by Django 4.1.7 on 2023-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='approved', max_length=20),
        ),
    ]
