# Generated by Django 4.1.7 on 2023-03-20 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_outs', to='attendance.attendance'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='is_check_in',
            field=models.BooleanField(default=False),
        ),
    ]
