# Generated by Django 4.1.7 on 2023-03-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_checkinout_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='time',
            field=models.TimeField(),
        ),
    ]
