# Generated by Django 4.1.7 on 2023-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_checkinout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
