# Generated by Django 4.1.7 on 2023-05-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_hr_manager',
            field=models.BooleanField(default=False),
        ),
    ]
