# Generated by Django 4.1.7 on 2023-03-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
