# Generated by Django 4.1.7 on 2023-05-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_remove_contact_employee_remove_contact_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
