# Generated by Django 4.1.7 on 2023-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
