# Generated by Django 4.1.7 on 2023-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_alter_holiday_date_alter_holiday_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
