# Generated by Django 4.1.7 on 2023-04-28 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_employeesalary_salary_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('employee_salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slip', to='salary.employeesalary')),
            ],
        ),
    ]
