# Generated by Django 4.1.7 on 2023-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_employeesalaryslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalaryslip',
            name='month',
        ),
        migrations.AddField(
            model_name='employeesalaryslip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
