# Generated by Django 4.1.7 on 2023-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_remove_employeesalaryslip_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='payslip_request',
            field=models.BooleanField(default=False),
        ),
    ]
